### ISSUE TITLE
Add PWA Installation screenshots

### ISSUE THREAD

**Issue by Parajulibkrm** [PoskOfficial/Nepali-calendar-web#24]

**Comment by nabin-kandel** [comment]
![Image](https://github.com/PoskOfficial/Nepali-calendar-web/assets/105159506/3c8e8d4a-6313-4504-86c1-fe3ac414d1d8)
![Image](https://github.com/PoskOfficial/Nepali-calendar-web/assets/105159506/40491e63-c9a0-47a3-a15d-c6627de087da)
![Image](https://github.com/PoskOfficial/Nepali-calendar-web/assets/105159506/d690d3b1-789e-4dfe-9733-3377a5a8fdb4)
![Image](https://github.com/PoskOfficial/Nepali-calendar-web/assets/105159506/30754306-1fd7-4704-958a-6cbcef63f2b8)
![Image](https://github.com/PoskOfficial/Nepali-calendar-web/assets/105159506/a0cd4321-feee-49e4-b196-45b8c3464c95)

**Comment by Parajulibkrm** [comment]
Thank you @nabin-kandel
