### ISSUE TITLE
Create Logo and Branding

### ISSUE THREAD

**Issue by Parajulibkrm** [PoskOfficial/Nepali-calendar-web#28]

**Comment by Bibekdhkl** [comment]
I guess I can help with this

**Comment by Parajulibkrm** [comment]
Please go ahead. You might want to adhere to some standard practices mentioned here
[https://looka.com/blog/app-logo/](https://looka.com/blog/app-logo/)

Do note that there might be other contributors with their own design as well, in that case, the team will have to contest between the submissions and choose the best ones. 

The primary color used in the app is currently #4f46e5 (indigo-600)
You can get the pallette from tailwind's indigo color series.

**Comment by nabin-kandel** [comment]
app_logo🫣

![1024 variant](https://github.com/PoskOfficial/Nepali-calendar-web/assets/105159506/c8a2e9b3-9c2c-4b63-bb8b-6a58d1523a00)

**Comment by Parajulibkrm** [comment]
LGTM, thanks
