### ISSUE TITLE
Incorrect Converted Date on Gregorian Date Picker in Date Conversion

### ISSUE THREAD

**Issue by Sajan-poudel** [PoskOfficial/Nepali-calendar-web#53]
**Describe the bug**
when you try to convert the nepali date to english it is showing to different dates. Below one is correct though.

**To Reproduce**
1. Go to 'https://miti.bikram.io/converter (Date converter)'
2. Click on 'Date converter'
3. Give nepali date (e.g 2056/6/22)
4. give two different dates

**Expected behavior**
for 2056/6/22 it should be 1999/10/09 

**Screenshots**
![image](https://github.com/PoskOfficial/Nepali-calendar-web/assets/51732201/1d98daad-6505-4ad8-bbaa-f6d7e42a1a80)

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser: Chrome
 - Version 114.0.5735.199

**Comment by Parajulibkrm** [comment]
@nirajacharyaa @headshigh  could you guys take a look?

**Comment by Parajulibkrm** [comment]
@pandeysubash404  would you like to fix this one?

**Comment by pandeysubash404** [comment]
> @pandeysubash404 would you like to fix this one?
     @Parajulibkrm  I have already fix the bug  with my issue #57 and now it is in production too 

<img width="960" alt="Miti5" src="https://github.com/PoskOfficial/Nepali-calendar-web/assets/71953734/0a5909ac-1f95-4fc4-9788-b34e270e6a68">
