### ISSUE TITLE
sign in with google permission not working properly

### ISSUE THREAD

**Issue by aashisham** [PoskOfficial/Nepali-calendar-web#55]
**Describe the bug**
Google permission is not working properly.  Login without permission at first and revoke it to log in again with all permissions, the permissions won't work. 

**To Reproduce**
1.  Go to sign in with Google and give only the first permission(or none) while signing in.
2.  Create an event on any date, you can't choose the calendar from the list so the event is not created.
3.  Go to the security setting of your Google account and revoke permission with Miti.
4.  Go to sign in with Google again and give all permissions and continue.
5.  Try creating an event and you still can't choose the calendar from the list so the event is not created.

**Expected behavior**
After revoking the connection from my Google account, signing in again with all permissions should give me all permissions to create, and edit events. 

**Screenshots**
Here are some of the screenshots that might be useful to understand the problem : 
Permission screen : 
![1689662810507](https://github.com/PoskOfficial/Nepali-calendar-web/assets/33601771/5c89f1cc-2064-4ad4-90c7-646cc0032f92)

Event creation (can't choose calendar ) :
![1689662810486](https://github.com/PoskOfficial/Nepali-calendar-web/assets/33601771/a1207158-cc48-4d68-81c2-1b77e3b283a5)

Revoking access from Google : 
![1689662810528](https://github.com/PoskOfficial/Nepali-calendar-web/assets/33601771/b01f3ca4-9b7f-46bb-876c-ed7707ee771c)

**Smartphone (please complete the following information):**
 - Device: [ Xioami]
 - OS: [ android 11]
 - Browser [ chrome]
 - Version [107.0.5304.105]

**Comment by Parajulibkrm** [comment]
Could you please check if this is fixed?
