### ISSUE TITLE
Day Calculation One Day Faster in Asia/Kathmandu Time Zone

### ISSUE THREAD

**Issue by pandeysubash404** [PoskOfficial/Nepali-calendar-web#58]
**Issue Description:**

The current implementation of day calculation in the Asia/Kathmandu time zone is resulting in events being displayed one day ahead of their actual date. This issue affects users who are using the Nepali calendar or are located in the Kathmandu time zone.

**Steps to Reproduce:**

1. Create an event in the Miti calendar application with a specific date (e.g., July 20, 2023) using the Nepali calendar or while in the Asia/Kathmandu time zone.
2. Save the event and verify its date in the Miti calendar.

**Expected Behavior:**

The event should be displayed on the correct date, matching the date accordingly in the Nepali calendar or the local Asia/Kathmandu time zone.

**Actual Behavior:**

The event is displayed one day ahead of the entered date. For example, today is July 20,2023 but it will label as _yesterday_ .

**Additional Information:**

- The issue appears to be specific to the Asia/Kathmandu time zone or when using the Nepali calendar, as events in other time zones or calendars do not exhibit this behavior.
- This problem can lead to confusion and mismanagement of schedules, potentially causing users to miss important events or appointments.

**Proposed Solution:**

The issue seems to be related to the day calculation logic used when displaying events in the Asia/Kathmandu time zone or using the Nepali calendar. To resolve this problem, the day calculation algorithm needs to be thoroughly reviewed and adjusted to ensure accurate date representation for events in the affected time zone.

One possible approach to investigate is to verify if there are any discrepancies in the conversion between the Gregorian and Nepali calendars within the Miti codebase. Additionally, it may be necessary to consider potential issues related to time zone offset calculations and DST (Daylight Saving Time) adjustments.

**Attachments:**

<img width="962" alt="Miti1" src="https://github.com/PoskOfficial/Nepali-calendar-web/assets/71953734/d2dbcda5-a6e8-4616-b03a-9a1e7d9dc114">

- The issue is generated from the code 
```
/**
 * Get language-sensitive relative time message from Dates.
 * @param relative  - the relative dateTime, generally is in the past or future
 * @param pivot     - the dateTime of reference, generally is the current time
 */
export function relativeTimeFromDates(
  relative: Date | null,
  isNepaliLanguage = false,
  pivot = new Date()
): string {
  if (!relative) return "";
  const elapsed = relative.getTime() - pivot.getTime();
  return relativeTimeFromElapsed(elapsed, isNepaliLanguage);
}
```
I am eager to contribute to resolving this issue and help enhance the functionality of the Miti calendar application for users in the Asia/Kathmandu time zone. Please let me know how I can be of further assistance in addressing this matter.

Best regards,
Subash Pandey
pandeysubash404@gmail.com
2023, July 21

**Comment by Parajulibkrm** [comment]
Acknowledged. Please take a look into this @headshigh

**Comment by pandeysubash404** [comment]
> @pandeysubash404 Would you like to open a PR for this issue?
@Parajulibkrm Yes, I'd be happy to open a PR for this issue!

Additionally, I want to display today's date on the Events. Even if there are no events on a particular day, displaying today's date will help avoid confusion when comparing event days. I'll make sure to implement this improvement in the PR.

**Comment by Parajulibkrm** [comment]
I'm not sure if I understand what you mean there, could you elaborate a little about displaying "today's date"? Also, please go ahead with the PR.

**Comment by pandeysubash404** [comment]
> I'm not sure if I understand what you mean there, could you elaborate a little about displaying "today's date"? Also, please go ahead with the PR.

Hope the with the help of below image , you can understand what i want to make change.
      The below image is after making the change, which (2023 July 20 , Friday) do not have any event but also being displayed. I think it will help to avoid confusion when comparing event days.

<img width="960" alt="Miti3" src="https://github.com/PoskOfficial/Nepali-calendar-web/assets/71953734/988a8a0f-62a9-474d-8f6d-c21ee756b9cc">

**Comment by Parajulibkrm** [comment]
Sure go ahead.

**Comment by pandeysubash404** [comment]
Hi @Parajulibkrm ,

I wanted to let you know that I have successfully submitted my contribution to solve the issue  (#58) regarding the event display one day ahead of the entered date. I have created a pull request (PR) with my changes on the branch "event-display". Please review the changes whenever you get a chance.

Additionally, I have taken into consideration the suggestion you made about displaying today's date even if there is no event occurring. This would help avoid confusion while comparing event days.

If there's anything else you'd like me to do or any further improvements you'd like to see, please let me know. I'm looking forward to your feedback.

Best regards,
@pandeysubash404
