### ISSUE TITLE
Layout shifts when events are loaded

### ISSUE THREAD

**Issue by nbnsresta** [PoskOfficial/Nepali-calendar-web#70]
**Describe the bug**
The layout of the calendar shifts quite a bit after the calendar events are loaded.

**To Reproduce**
1. Go to any month
2. Notice the size of the day cell change once the events are loaded.

**Expected behavior**
The cell size should stay the same. Best if a square. It also helps make the row heights more consistent.

**Screenshots**

**Additional context**

**Comment by nirajacharyaa** [comment]
Can you fix this too ?? @nbnsresta

**Comment by nbnsresta** [comment]
sure.  @nirajacharyaa

**Comment by Parajulibkrm** [comment]
Fixed by #72
