### ISSUE TITLE
Port Lucia Auth to Oslo

### ISSUE THREAD

**Issue by Parajulibkrm** [PoskOfficial/Nepali-calendar-web#82]
Lucia-auth is deprecating [know more](https://github.com/lucia-auth/lucia/discussions/1714) and it will be replaced by [Oslo](https://oslo.js.org/). Oslo provides utility functions that lucia internally calls so that we can take database logic out of Lucia. 
Port to use just oslo so that we don't rely on something that is going to be deprecated soon.

**Comment by Parajulibkrm** [comment]
Here's a [resource](https://www.youtube.com/watch?v=Blx0roWAsFQ) that might help with this.

**Comment by Parajulibkrm** [comment]
Here's the official [doc](https://lucia-next.pages.dev/) (which may be changed in the future though).

**Comment by axyut** [comment]
can you assign this to me

**Comment by nirajacharyaa** [comment]
Thanks @axyut :confetti_ball:
